"""
Generates a professional PDF screening report using ReportLab.

Structure:
  - Header with report metadata
  - Screening summary table
  - Visual insights (charts + key metrics)
  - Per-vendor findings table (colour-coded)
  - AI narrative section (if present)
  - Footer with page numbers and timestamp
"""
import io
from collections import Counter
from datetime import datetime, timezone

from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.shapes import Drawing, String
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from database.models import MatchStatus, ScreeningRun

# Colours
_NAVY = colors.HexColor("#1F4E79")
_RED = colors.HexColor("#C00000")
_AMBER = colors.HexColor("#ED7D31")
_GREEN = colors.HexColor("#70AD47")
_BLUE = colors.HexColor("#2F5597")
_LIGHT_GREY = colors.HexColor("#F2F2F2")
_MID_GREY = colors.HexColor("#D9D9D9")

_STATUS_COLOUR = {
    MatchStatus.FLAGGED: _RED,
    MatchStatus.REVIEW: _AMBER,
    MatchStatus.CLEAR: _GREEN,
}
_STATUS_LABEL = {
    MatchStatus.FLAGGED: "FLAGGED",
    MatchStatus.REVIEW: "REVIEW",
    MatchStatus.CLEAR: "CLEAR",
}


def _make_styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"], fontSize=18, textColor=_NAVY, spaceAfter=4),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"], fontSize=10, textColor=colors.grey, spaceAfter=12),
        "section": ParagraphStyle("section", parent=base["Heading2"], fontSize=12, textColor=_NAVY, spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("body", parent=base["Normal"], fontSize=9, leading=13, spaceAfter=6),
        "cell": ParagraphStyle("cell", parent=base["Normal"], fontSize=8, leading=11),
    }


def _make_page_template(canvas, doc):
    canvas.saveState()
    width, height = A4

    canvas.setFillColor(_NAVY)
    canvas.rect(0, height - 1.5 * cm, width, 1.5 * cm, fill=True, stroke=False)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(1.5 * cm, height - 1.0 * cm, "TRADE SANCTIONS SCREENING REPORT")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(width - 1.5 * cm, height - 1.0 * cm, f"CONFIDENTIAL - {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")

    canvas.setFillColor(_NAVY)
    canvas.rect(0, 0, width, 0.8 * cm, fill=True, stroke=False)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(1.5 * cm, 0.25 * cm, "Generated by Trade Sanctions Screening Tool v1.0")
    canvas.drawRightString(width - 1.5 * cm, 0.25 * cm, f"Page {doc.page}")

    canvas.restoreState()


def _count_statuses(run: ScreeningRun) -> tuple[int, int, int]:
    flagged = sum(1 for r in run.results if r.status == MatchStatus.FLAGGED)
    review = sum(1 for r in run.results if r.status == MatchStatus.REVIEW)
    clear = sum(1 for r in run.results if r.status == MatchStatus.CLEAR)
    return flagged, review, clear


def _summary_table(run: ScreeningRun) -> Table:
    flagged, review, clear = _count_statuses(run)

    data = [
        ["Report ID", f"SCR-{run.id:06d}", "Customer", run.customer_name or "-"],
        ["Screening Duration", f"{run.elapsed_seconds:.2f}s" if run.elapsed_seconds else "-", "Generated At", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")],
        ["Vendors Screened", str(len(run.results)), "Run Status", run.status.value.upper()],
        ["Flagged", str(flagged), "Review Needed", str(review)],
        ["Clear", str(clear), "", ""],
    ]

    t = Table(data, colWidths=[3.8 * cm, 4.8 * cm, 3.8 * cm, 4.8 * cm])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), _LIGHT_GREY),
                ("BACKGROUND", (2, 0), (2, -1), _LIGHT_GREY),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, _MID_GREY),
                ("ROWBACKGROUNDS", (1, 0), (-1, -1), [colors.white, _LIGHT_GREY]),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("TEXTCOLOR", (1, 3), (1, 3), _RED),
                ("FONTNAME", (1, 3), (1, 3), "Helvetica-Bold"),
                ("TEXTCOLOR", (3, 3), (3, 3), _AMBER),
                ("FONTNAME", (3, 3), (3, 3), "Helvetica-Bold"),
                ("TEXTCOLOR", (1, 4), (1, 4), _GREEN),
                ("FONTNAME", (1, 4), (1, 4), "Helvetica-Bold"),
            ]
        )
    )
    return t


def _outcome_pie_chart(run: ScreeningRun) -> Drawing:
    flagged, review, clear = _count_statuses(run)
    values = [flagged, review, clear]

    drawing = Drawing(8.2 * cm, 6.0 * cm)
    drawing.add(String(5, 5.4 * cm, "Outcome Mix", fontName="Helvetica-Bold", fontSize=9, fillColor=_NAVY))

    pie = Pie()
    pie.x = 0.6 * cm
    pie.y = 0.3 * cm
    pie.width = 4.6 * cm
    pie.height = 4.6 * cm
    pie.data = values if sum(values) > 0 else [1, 1, 1]
    pie.labels = ["Flagged", "Review", "Clear"]
    pie.slices.strokeWidth = 0.3
    pie.slices[0].fillColor = _RED
    pie.slices[1].fillColor = _AMBER
    pie.slices[2].fillColor = _GREEN
    drawing.add(pie)

    drawing.add(String(5.8 * cm, 3.9 * cm, f"Flagged: {flagged}", fontSize=8, fillColor=_RED))
    drawing.add(String(5.8 * cm, 3.4 * cm, f"Review: {review}", fontSize=8, fillColor=_AMBER))
    drawing.add(String(5.8 * cm, 2.9 * cm, f"Clear: {clear}", fontSize=8, fillColor=_GREEN))
    return drawing


def _source_bar_chart(run: ScreeningRun) -> Drawing:
    counts = Counter((r.list_source or "Unknown") for r in run.results)
    top_sources = counts.most_common(5)

    labels = [item[0] for item in top_sources] or ["No Data"]
    values = [item[1] for item in top_sources] or [0]

    drawing = Drawing(8.2 * cm, 6.0 * cm)
    drawing.add(String(5, 5.4 * cm, "Top List Sources", fontName="Helvetica-Bold", fontSize=9, fillColor=_NAVY))

    chart = VerticalBarChart()
    chart.x = 0.8 * cm
    chart.y = 0.9 * cm
    chart.width = 6.8 * cm
    chart.height = 3.9 * cm
    chart.data = [values]
    chart.categoryAxis.categoryNames = labels
    chart.categoryAxis.labels.fontSize = 7
    chart.categoryAxis.labels.angle = 20
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueStep = max(1, (max(values) // 4) or 1)
    chart.valueAxis.labels.fontSize = 7
    chart.bars[0].fillColor = _BLUE
    chart.bars[0].strokeColor = _NAVY
    chart.barLabelFormat = "%d"
    chart.barLabels.nudge = 6
    chart.barLabels.fontSize = 7
    chart.barLabels.fillColor = _NAVY

    drawing.add(chart)
    return drawing




def _screening_trend_chart(run: ScreeningRun) -> Drawing:
    """Single-run trend snapshot aligned to the selected run only."""
    flagged, review, clear = _count_statuses(run)
    screenings = len(run.results)
    matches = flagged
    date_label = run.started_at.strftime("%Y-%m-%d") if run.started_at else "Run Date"

    drawing = Drawing(8.2 * cm, 6.0 * cm)
    drawing.add(String(5, 5.4 * cm, "Screening Trends", fontName="Helvetica-Bold", fontSize=9, fillColor=_NAVY))

    chart = VerticalBarChart()
    chart.x = 0.8 * cm
    chart.y = 0.9 * cm
    chart.width = 6.8 * cm
    chart.height = 3.9 * cm
    chart.data = [[screenings], [matches]]
    chart.categoryAxis.categoryNames = [date_label]
    chart.categoryAxis.labels.fontSize = 7
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueStep = max(1, (max(screenings, matches) // 4) or 1)
    chart.valueAxis.labels.fontSize = 7
    chart.bars[0].fillColor = _BLUE
    chart.bars[0].strokeColor = _NAVY
    chart.bars[1].fillColor = _RED
    chart.bars[1].strokeColor = _NAVY
    chart.barLabelFormat = "%d"
    chart.barLabels.nudge = 6
    chart.barLabels.fontSize = 7
    chart.barLabels.fillColor = _NAVY

    drawing.add(chart)
    drawing.add(String(5.1 * cm, 4.6 * cm, "Blue: Screened", fontSize=7, fillColor=_BLUE))
    drawing.add(String(5.1 * cm, 4.2 * cm, "Red: Flagged", fontSize=7, fillColor=_RED))
    return drawing


def _run_status_mix_chart(run: ScreeningRun) -> Drawing:
    """Run-status mix for this selected run only."""
    status = (run.status.value if hasattr(run.status, "value") else str(run.status)).lower()
    completed = 1 if status == "complete" else 0
    failed = 1 if status == "failed" else 0
    values = [completed, failed]

    drawing = Drawing(8.2 * cm, 6.0 * cm)
    drawing.add(String(5, 5.4 * cm, "Run Status Mix", fontName="Helvetica-Bold", fontSize=9, fillColor=_NAVY))

    pie = Pie()
    pie.x = 0.6 * cm
    pie.y = 0.3 * cm
    pie.width = 4.6 * cm
    pie.height = 4.6 * cm
    pie.data = values if sum(values) > 0 else [1, 1]
    pie.labels = ["Completed", "Failed"]
    pie.slices.strokeWidth = 0.3
    pie.slices[0].fillColor = _BLUE
    pie.slices[1].fillColor = _RED
    drawing.add(pie)

    drawing.add(String(5.8 * cm, 3.9 * cm, f"Completed: {completed}", fontSize=8, fillColor=_BLUE))
    drawing.add(String(5.8 * cm, 3.4 * cm, f"Failed: {failed}", fontSize=8, fillColor=_RED))
    return drawing

def _insight_metrics_table(run: ScreeningRun) -> Table:
    flagged, review, clear = _count_statuses(run)
    total = len(run.results)
    hit_rate = ((flagged + review) / total * 100.0) if total else 0.0
    escalation_rate = (flagged / total * 100.0) if total else 0.0

    data = [
        ["Hit Rate (Flagged + Review)", f"{hit_rate:.1f}%"],
        ["Escalation Rate (Flagged)", f"{escalation_rate:.1f}%"],
        ["Total Entities Screened", str(total)],
        ["Highest Risk Count", str(max(flagged, review, clear) if total else 0)],
    ]

    t = Table(data, colWidths=[6.2 * cm, 2.8 * cm])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), _LIGHT_GREY),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
                ("TEXTCOLOR", (1, 0), (1, 1), _NAVY),
                ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                ("GRID", (0, 0), (-1, -1), 0.4, _MID_GREY),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return t


def _visual_insights_block(run: ScreeningRun) -> list:
    left = _outcome_pie_chart(run)
    right = _source_bar_chart(run)
    lower_left = _screening_trend_chart(run)
    lower_right = _run_status_mix_chart(run)

    chart_table = Table([[left, right], [lower_left, lower_right]], colWidths=[8.2 * cm, 8.2 * cm])
    chart_table.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))

    return [chart_table, Spacer(1, 0.25 * cm), _insight_metrics_table(run)]



def _clean_text(value: object) -> str:
    text = str(value or "-").strip()
    # Normalize common mojibake / dash variants that can render poorly in PDF cells.
    text = text.replace("\u2014", "-").replace("\u2013", "-")
    text = text.replace("\ufffd", "-")
    text = text.replace("â€”", "-")
    return text or "-"

def _format_list_source(value: object) -> str:
    text = _clean_text(value)
    # Add soft wrap opportunities for long source tokens.
    text = text.replace('_', '_ ').replace('/', '/ ').replace('-', '- ').replace(',', ', ')
    return ' '.join(text.split())

def _results_table(run: ScreeningRun, styles: dict) -> Table:
    headers = ["Vendor Name", "Status", "Score", "Matched Entity", "List", "Tier"]
    col_w = [4.3 * cm, 2.0 * cm, 1.4 * cm, 3.9 * cm, 3.1 * cm, 1.3 * cm]

    rows = [headers]
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, _MID_GREY),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _LIGHT_GREY]),
    ]

    for i, r in enumerate(run.results, start=1):
        label = _STATUS_LABEL.get(r.status, r.status.value)
        colour = _STATUS_COLOUR.get(r.status, _GREEN)
        score = f"{r.match_score:.0f}%" if r.match_score else "-"

        rows.append(
            [
                Paragraph(_clean_text(r.vendor_name), styles["cell"]),
                Paragraph(_clean_text(label), styles["cell"]),
                score,
                Paragraph(_clean_text(r.matched_name), styles["cell"]),
                Paragraph(_format_list_source(r.list_source), styles["cell"]),
                Paragraph(_clean_text(f"Tier {r.tier}" if r.tier else "-"), styles["cell"]),
            ]
        )
        style_cmds += [
            ("TEXTCOLOR", (1, i), (1, i), colour),
            ("FONTNAME", (1, i), (1, i), "Helvetica-Bold"),
        ]

    t = Table(rows, colWidths=col_w, repeatRows=1)
    t.setStyle(TableStyle(style_cmds))
    return t


def generate_pdf(run: ScreeningRun) -> bytes:
    """Return PDF report as bytes (ready to stream via HTTP response)."""
    buf = io.BytesIO()
    styles = _make_styles()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=2.2 * cm,
        bottomMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
    )

    story = []

    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph("Sanctions Screening Report", styles["title"]))
    story.append(
        Paragraph(
            f"Customer: <b>{run.customer_name or '-'}</b> &nbsp;|&nbsp; Report ID: <b>SCR-{run.id:06d}</b>",
            styles["subtitle"],
        )
    )
    story.append(HRFlowable(width="100%", thickness=1, color=_NAVY, spaceAfter=10))

    story.append(Paragraph("Screening Summary", styles["section"]))
    story.append(_summary_table(run))
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Visual Insights", styles["section"]))
    story.extend(_visual_insights_block(run))
    story.append(Spacer(1, 0.6 * cm))

    story.append(Paragraph("Vendor Screening Results", styles["section"]))
    story.append(_results_table(run, styles))
    story.append(Spacer(1, 0.6 * cm))

    if run.ai_summary:
        story.append(PageBreak())
        story.append(Paragraph("AI Compliance Analysis", styles["section"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=_MID_GREY, spaceAfter=8))
        for para in run.ai_summary.split("\n\n"):
            if para.strip():
                story.append(Paragraph(para.strip(), styles["body"]))
                story.append(Spacer(1, 0.2 * cm))

    doc.build(story, onFirstPage=_make_page_template, onLaterPages=_make_page_template)
    buf.seek(0)
    return buf.read()







